insert into songs (Title, Artist, Genre) values ('1984', 'John Smith', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'David Thompson', 'adventure');
insert into songs (Title, Artist, Genre) values ('1984', 'Emily Johnson', 'romance');
insert into songs (Title, Artist, Genre) values ('1984', 'David Thompson', 'drama');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Emily Johnson', 'drama');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Michael Davis', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'David Thompson', 'action');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'David Thompson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Michael Davis', 'mystery');
insert into songs (Title, Artist, Genre) values ('1984', 'Michael Davis', 'comedy');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Michael Davis', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'John Smith', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emma Wilson', 'action');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Michael Davis', 'fantasy');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emily Johnson', 'thriller');
insert into songs (Title, Artist, Genre) values ('1984', 'Emma Wilson', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'John Smith', 'drama');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Emma Wilson', 'mystery');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emily Johnson', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Michael Davis', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'John Smith', 'fantasy');
insert into songs (Title, Artist, Genre) values ('1984', 'Michael Davis', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Emma Wilson', 'romance');
insert into songs (Title, Artist, Genre) values ('1984', 'Emily Johnson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'John Smith', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Michael Davis', 'mystery');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emily Johnson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emily Johnson', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'John Smith', 'horror');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emily Johnson', 'romance');
insert into songs (Title, Artist, Genre) values ('1984', 'John Smith', 'action');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Michael Davis', 'thriller');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'John Smith', 'drama');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emma Wilson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Emma Wilson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'David Thompson', 'romance');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'John Smith', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Michael Davis', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emma Wilson', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Michael Davis', 'fantasy');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emma Wilson', 'action');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Michael Davis', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'David Thompson', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Emily Johnson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Emma Wilson', 'drama');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Emma Wilson', 'romance');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emily Johnson', 'mystery');
insert into songs (Title, Artist, Genre) values ('1984', 'David Thompson', 'drama');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Emily Johnson', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Emma Wilson', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'John Smith', 'horror');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emily Johnson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emily Johnson', 'drama');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emma Wilson', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emma Wilson', 'action');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'John Smith', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'David Thompson', 'action');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Emily Johnson', 'horror');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'David Thompson', 'drama');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emma Wilson', 'romance');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'John Smith', 'action');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emma Wilson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emily Johnson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Emily Johnson', 'mystery');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'David Thompson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('1984', 'David Thompson', 'adventure');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'John Smith', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'David Thompson', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'David Thompson', 'thriller');
insert into songs (Title, Artist, Genre) values ('1984', 'Emma Wilson', 'adventure');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emma Wilson', 'action');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Michael Davis', 'mystery');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'John Smith', 'thriller');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emma Wilson', 'action');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Michael Davis', 'romance');
insert into songs (Title, Artist, Genre) values ('1984', 'Emma Wilson', 'action');
insert into songs (Title, Artist, Genre) values ('1984', 'John Smith', 'adventure');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emma Wilson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Michael Davis', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Michael Davis', 'romance');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'David Thompson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Emma Wilson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Michael Davis', 'adventure');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emma Wilson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'John Smith', 'horror');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Michael Davis', 'romance');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emma Wilson', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emily Johnson', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Michael Davis', 'romance');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Emily Johnson', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Emma Wilson', 'adventure');
insert into songs (Title, Artist, Genre) values ('1984', 'John Smith', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'John Smith', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Michael Davis', 'thriller');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'David Thompson', 'romance');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Emily Johnson', 'horror');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'David Thompson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'David Thompson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emily Johnson', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'John Smith', 'adventure');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'David Thompson', 'action');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Emily Johnson', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Emily Johnson', 'mystery');
insert into songs (Title, Artist, Genre) values ('1984', 'Michael Davis', 'horror');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'David Thompson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emma Wilson', 'horror');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'David Thompson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('1984', 'David Thompson', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Michael Davis', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'David Thompson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'David Thompson', 'romance');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Michael Davis', 'drama');
insert into songs (Title, Artist, Genre) values ('1984', 'David Thompson', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'David Thompson', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'David Thompson', 'drama');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Emma Wilson', 'romance');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'David Thompson', 'drama');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Michael Davis', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Michael Davis', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'John Smith', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'David Thompson', 'romance');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emily Johnson', 'drama');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'David Thompson', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Emma Wilson', 'mystery');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emily Johnson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Michael Davis', 'horror');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Michael Davis', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Emily Johnson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Michael Davis', 'action');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Michael Davis', 'thriller');
insert into songs (Title, Artist, Genre) values ('1984', 'Emma Wilson', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'David Thompson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('1984', 'Emily Johnson', 'horror');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Michael Davis', 'romance');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'David Thompson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'David Thompson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Michael Davis', 'romance');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emma Wilson', 'mystery');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'John Smith', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Emma Wilson', 'action');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'David Thompson', 'horror');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emily Johnson', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'John Smith', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Michael Davis', 'drama');
insert into songs (Title, Artist, Genre) values ('1984', 'Emma Wilson', 'mystery');
insert into songs (Title, Artist, Genre) values ('1984', 'Michael Davis', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Emma Wilson', 'action');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emma Wilson', 'action');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emma Wilson', 'action');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'John Smith', 'drama');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emma Wilson', 'horror');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'David Thompson', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Emily Johnson', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emily Johnson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'David Thompson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Emma Wilson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'David Thompson', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Emily Johnson', 'drama');
insert into songs (Title, Artist, Genre) values ('1984', 'Emily Johnson', 'action');
insert into songs (Title, Artist, Genre) values ('1984', 'John Smith', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Michael Davis', 'romance');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'David Thompson', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emily Johnson', 'drama');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'John Smith', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'John Smith', 'action');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emily Johnson', 'comedy');
insert into songs (Title, Artist, Genre) values ('1984', 'Emily Johnson', 'romance');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'David Thompson', 'horror');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Michael Davis', 'drama');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'John Smith', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Emily Johnson', 'action');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emma Wilson', 'adventure');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emma Wilson', 'romance');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Emma Wilson', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Michael Davis', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'David Thompson', 'comedy');
insert into songs (Title, Artist, Genre) values ('1984', 'John Smith', 'romance');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'John Smith', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emily Johnson', 'horror');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emily Johnson', 'adventure');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Michael Davis', 'action');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'John Smith', 'adventure');
insert into songs (Title, Artist, Genre) values ('1984', 'Emma Wilson', 'romance');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Emily Johnson', 'horror');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'David Thompson', 'horror');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emma Wilson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emily Johnson', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emily Johnson', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emma Wilson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Emily Johnson', 'comedy');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'David Thompson', 'adventure');
insert into songs (Title, Artist, Genre) values ('1984', 'Emily Johnson', 'romance');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Michael Davis', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'David Thompson', 'action');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emily Johnson', 'action');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emma Wilson', 'action');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emily Johnson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emma Wilson', 'thriller');
insert into songs (Title, Artist, Genre) values ('1984', 'Michael Davis', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'John Smith', 'romance');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emma Wilson', 'horror');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'David Thompson', 'thriller');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'David Thompson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('1984', 'John Smith', 'drama');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Michael Davis', 'action');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'John Smith', 'romance');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'David Thompson', 'horror');
insert into songs (Title, Artist, Genre) values ('1984', 'David Thompson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'John Smith', 'romance');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Emily Johnson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'David Thompson', 'adventure');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emma Wilson', 'mystery');
insert into songs (Title, Artist, Genre) values ('1984', 'John Smith', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'David Thompson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Michael Davis', 'mystery');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emma Wilson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'David Thompson', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'John Smith', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'John Smith', 'horror');
insert into songs (Title, Artist, Genre) values ('1984', 'Emma Wilson', 'horror');
insert into songs (Title, Artist, Genre) values ('1984', 'Emma Wilson', 'action');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Michael Davis', 'romance');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Michael Davis', 'thriller');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emma Wilson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Michael Davis', 'action');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emma Wilson', 'action');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'David Thompson', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'John Smith', 'horror');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Michael Davis', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emily Johnson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Emma Wilson', 'mystery');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Michael Davis', 'action');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emily Johnson', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Emma Wilson', 'action');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'David Thompson', 'drama');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'John Smith', 'drama');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Michael Davis', 'comedy');
insert into songs (Title, Artist, Genre) values ('1984', 'David Thompson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'John Smith', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Michael Davis', 'romance');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emily Johnson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'David Thompson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emily Johnson', 'romance');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emily Johnson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'David Thompson', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emily Johnson', 'drama');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'John Smith', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'David Thompson', 'mystery');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Michael Davis', 'comedy');
insert into songs (Title, Artist, Genre) values ('1984', 'Michael Davis', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'John Smith', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Emma Wilson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Emma Wilson', 'romance');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Michael Davis', 'romance');
insert into songs (Title, Artist, Genre) values ('1984', 'Emily Johnson', 'adventure');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emily Johnson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'David Thompson', 'thriller');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'David Thompson', 'action');
insert into songs (Title, Artist, Genre) values ('1984', 'David Thompson', 'comedy');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Michael Davis', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'David Thompson', 'drama');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'David Thompson', 'comedy');
insert into songs (Title, Artist, Genre) values ('1984', 'John Smith', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'David Thompson', 'action');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'John Smith', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'David Thompson', 'mystery');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emma Wilson', 'romance');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'David Thompson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emily Johnson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'David Thompson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emma Wilson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Michael Davis', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'David Thompson', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emma Wilson', 'comedy');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emma Wilson', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emily Johnson', 'horror');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emma Wilson', 'horror');
insert into songs (Title, Artist, Genre) values ('1984', 'Michael Davis', 'action');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'David Thompson', 'action');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'David Thompson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'John Smith', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Emily Johnson', 'thriller');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Michael Davis', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'David Thompson', 'drama');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'David Thompson', 'horror');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'David Thompson', 'romance');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Emma Wilson', 'romance');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Michael Davis', 'action');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Michael Davis', 'drama');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emma Wilson', 'mystery');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Michael Davis', 'romance');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emily Johnson', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emma Wilson', 'adventure');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emily Johnson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Emma Wilson', 'action');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emma Wilson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('1984', 'John Smith', 'adventure');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'David Thompson', 'thriller');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Michael Davis', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'David Thompson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('1984', 'John Smith', 'horror');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Michael Davis', 'drama');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emily Johnson', 'horror');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'John Smith', 'thriller');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'David Thompson', 'action');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emma Wilson', 'comedy');
insert into songs (Title, Artist, Genre) values ('1984', 'Emily Johnson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Michael Davis', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Emma Wilson', 'adventure');
insert into songs (Title, Artist, Genre) values ('1984', 'Emma Wilson', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emma Wilson', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emma Wilson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Emily Johnson', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'David Thompson', 'comedy');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emma Wilson', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Emily Johnson', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Michael Davis', 'fantasy');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emma Wilson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('1984', 'John Smith', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Michael Davis', 'romance');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'John Smith', 'thriller');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emma Wilson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'David Thompson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'John Smith', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Michael Davis', 'fantasy');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'John Smith', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'John Smith', 'mystery');
insert into songs (Title, Artist, Genre) values ('1984', 'Emily Johnson', 'romance');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emily Johnson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'David Thompson', 'action');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Emily Johnson', 'adventure');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'David Thompson', 'thriller');
insert into songs (Title, Artist, Genre) values ('1984', 'Emily Johnson', 'drama');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'David Thompson', 'romance');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'David Thompson', 'drama');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Emily Johnson', 'drama');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emily Johnson', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emily Johnson', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'David Thompson', 'drama');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Michael Davis', 'comedy');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'John Smith', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Michael Davis', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'David Thompson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Michael Davis', 'mystery');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'David Thompson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emma Wilson', 'drama');
insert into songs (Title, Artist, Genre) values ('1984', 'Emily Johnson', 'comedy');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'John Smith', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'John Smith', 'horror');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'John Smith', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Michael Davis', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'John Smith', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Michael Davis', 'comedy');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'John Smith', 'horror');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'John Smith', 'thriller');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Michael Davis', 'horror');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'John Smith', 'drama');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'David Thompson', 'drama');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Emma Wilson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('1984', 'Emma Wilson', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'John Smith', 'mystery');
insert into songs (Title, Artist, Genre) values ('1984', 'Emma Wilson', 'mystery');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'John Smith', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Emma Wilson', 'drama');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Michael Davis', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Michael Davis', 'action');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'David Thompson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Emily Johnson', 'romance');
insert into songs (Title, Artist, Genre) values ('1984', 'Michael Davis', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Michael Davis', 'romance');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'David Thompson', 'thriller');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emily Johnson', 'comedy');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emma Wilson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emily Johnson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'John Smith', 'action');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Emma Wilson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Michael Davis', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Emily Johnson', 'comedy');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'John Smith', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'David Thompson', 'romance');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Michael Davis', 'comedy');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'David Thompson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emma Wilson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'David Thompson', 'action');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emily Johnson', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Emma Wilson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Michael Davis', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Michael Davis', 'romance');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'John Smith', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Emily Johnson', 'horror');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emily Johnson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Emily Johnson', 'action');
insert into songs (Title, Artist, Genre) values ('1984', 'Michael Davis', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emma Wilson', 'drama');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emma Wilson', 'thriller');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'John Smith', 'horror');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Michael Davis', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emily Johnson', 'action');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'John Smith', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'David Thompson', 'romance');
insert into songs (Title, Artist, Genre) values ('1984', 'David Thompson', 'romance');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'David Thompson', 'action');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emily Johnson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emma Wilson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emma Wilson', 'horror');
insert into songs (Title, Artist, Genre) values ('1984', 'David Thompson', 'romance');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Michael Davis', 'fantasy');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Michael Davis', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emily Johnson', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emma Wilson', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'David Thompson', 'action');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'David Thompson', 'action');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emily Johnson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emma Wilson', 'thriller');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emily Johnson', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Michael Davis', 'mystery');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emily Johnson', 'romance');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emily Johnson', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Michael Davis', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'David Thompson', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'John Smith', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Michael Davis', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('1984', 'Michael Davis', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'John Smith', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Emma Wilson', 'romance');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emma Wilson', 'action');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Emma Wilson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'David Thompson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Michael Davis', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'John Smith', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'John Smith', 'romance');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'John Smith', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Michael Davis', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emily Johnson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Michael Davis', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'John Smith', 'comedy');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'John Smith', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'John Smith', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('1984', 'Emma Wilson', 'mystery');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'John Smith', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Emma Wilson', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Michael Davis', 'drama');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emma Wilson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Emma Wilson', 'comedy');
insert into songs (Title, Artist, Genre) values ('1984', 'Emily Johnson', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'John Smith', 'horror');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emily Johnson', 'drama');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emma Wilson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Michael Davis', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emma Wilson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'John Smith', 'fantasy');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'John Smith', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Michael Davis', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emily Johnson', 'comedy');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emma Wilson', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Michael Davis', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'John Smith', 'adventure');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Michael Davis', 'drama');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emma Wilson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'John Smith', 'horror');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'David Thompson', 'romance');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emily Johnson', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emily Johnson', 'drama');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emily Johnson', 'comedy');
insert into songs (Title, Artist, Genre) values ('1984', 'David Thompson', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emily Johnson', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emma Wilson', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Michael Davis', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emily Johnson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Emma Wilson', 'adventure');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'David Thompson', 'action');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emma Wilson', 'romance');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'John Smith', 'action');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Michael Davis', 'action');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Michael Davis', 'fantasy');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Michael Davis', 'mystery');
insert into songs (Title, Artist, Genre) values ('1984', 'David Thompson', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Michael Davis', 'comedy');
insert into songs (Title, Artist, Genre) values ('1984', 'John Smith', 'mystery');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'John Smith', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emily Johnson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emma Wilson', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Michael Davis', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Emma Wilson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Michael Davis', 'thriller');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'David Thompson', 'romance');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Michael Davis', 'thriller');
insert into songs (Title, Artist, Genre) values ('1984', 'David Thompson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'David Thompson', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emma Wilson', 'horror');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Michael Davis', 'drama');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Emma Wilson', 'thriller');
insert into songs (Title, Artist, Genre) values ('1984', 'David Thompson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Emma Wilson', 'drama');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Michael Davis', 'action');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Emily Johnson', 'drama');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emily Johnson', 'drama');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Michael Davis', 'horror');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'John Smith', 'thriller');
insert into songs (Title, Artist, Genre) values ('1984', 'John Smith', 'fantasy');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emily Johnson', 'romance');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emily Johnson', 'romance');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emily Johnson', 'action');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Michael Davis', 'horror');
insert into songs (Title, Artist, Genre) values ('1984', 'John Smith', 'horror');
insert into songs (Title, Artist, Genre) values ('1984', 'John Smith', 'drama');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Emily Johnson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emily Johnson', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Michael Davis', 'romance');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'David Thompson', 'romance');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emily Johnson', 'comedy');
insert into songs (Title, Artist, Genre) values ('1984', 'John Smith', 'horror');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'John Smith', 'thriller');
insert into songs (Title, Artist, Genre) values ('1984', 'David Thompson', 'horror');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emma Wilson', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'David Thompson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emma Wilson', 'adventure');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Michael Davis', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emma Wilson', 'mystery');
insert into songs (Title, Artist, Genre) values ('1984', 'Emma Wilson', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Michael Davis', 'fantasy');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emily Johnson', 'adventure');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'David Thompson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('1984', 'David Thompson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'David Thompson', 'horror');
insert into songs (Title, Artist, Genre) values ('1984', 'John Smith', 'mystery');
insert into songs (Title, Artist, Genre) values ('1984', 'John Smith', 'fantasy');
insert into songs (Title, Artist, Genre) values ('1984', 'Emma Wilson', 'mystery');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Michael Davis', 'action');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Michael Davis', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'David Thompson', 'drama');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Michael Davis', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Michael Davis', 'romance');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'David Thompson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Emily Johnson', 'drama');
insert into songs (Title, Artist, Genre) values ('1984', 'David Thompson', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'David Thompson', 'adventure');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emily Johnson', 'drama');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Michael Davis', 'fantasy');
insert into songs (Title, Artist, Genre) values ('1984', 'Emma Wilson', 'horror');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emma Wilson', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Michael Davis', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'David Thompson', 'action');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emily Johnson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Michael Davis', 'adventure');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Michael Davis', 'fantasy');
insert into songs (Title, Artist, Genre) values ('1984', 'Michael Davis', 'thriller');
insert into songs (Title, Artist, Genre) values ('1984', 'John Smith', 'drama');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emily Johnson', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'John Smith', 'drama');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Emma Wilson', 'action');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'John Smith', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Michael Davis', 'horror');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emma Wilson', 'adventure');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emma Wilson', 'action');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emma Wilson', 'mystery');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Michael Davis', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'John Smith', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emma Wilson', 'romance');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Michael Davis', 'drama');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'John Smith', 'romance');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'David Thompson', 'romance');
insert into songs (Title, Artist, Genre) values ('1984', 'John Smith', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emily Johnson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'David Thompson', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emily Johnson', 'comedy');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'David Thompson', 'drama');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Michael Davis', 'comedy');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emily Johnson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'David Thompson', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'John Smith', 'horror');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'David Thompson', 'mystery');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'David Thompson', 'mystery');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'John Smith', 'horror');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'John Smith', 'mystery');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Michael Davis', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Michael Davis', 'horror');
insert into songs (Title, Artist, Genre) values ('1984', 'Emily Johnson', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emily Johnson', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Emma Wilson', 'romance');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'John Smith', 'horror');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emma Wilson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'David Thompson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emily Johnson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Michael Davis', 'thriller');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'David Thompson', 'mystery');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'John Smith', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'John Smith', 'action');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Michael Davis', 'romance');
insert into songs (Title, Artist, Genre) values ('1984', 'Emma Wilson', 'action');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emma Wilson', 'romance');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'David Thompson', 'horror');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Michael Davis', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Michael Davis', 'action');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'John Smith', 'horror');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Michael Davis', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Michael Davis', 'comedy');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'John Smith', 'drama');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Emily Johnson', 'thriller');
insert into songs (Title, Artist, Genre) values ('1984', 'Michael Davis', 'horror');
insert into songs (Title, Artist, Genre) values ('1984', 'David Thompson', 'thriller');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emily Johnson', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Emily Johnson', 'mystery');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'David Thompson', 'adventure');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'David Thompson', 'drama');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'John Smith', 'action');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'John Smith', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'John Smith', 'romance');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Michael Davis', 'drama');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Michael Davis', 'action');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emma Wilson', 'mystery');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Michael Davis', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Michael Davis', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'David Thompson', 'action');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Michael Davis', 'horror');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'David Thompson', 'romance');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emma Wilson', 'thriller');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Michael Davis', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emma Wilson', 'drama');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Michael Davis', 'drama');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Michael Davis', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'David Thompson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emma Wilson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Michael Davis', 'romance');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'John Smith', 'action');
insert into songs (Title, Artist, Genre) values ('1984', 'Emily Johnson', 'action');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Emily Johnson', 'mystery');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'David Thompson', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Michael Davis', 'romance');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Michael Davis', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emma Wilson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'John Smith', 'fantasy');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emily Johnson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emily Johnson', 'action');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Emma Wilson', 'drama');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Michael Davis', 'romance');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Emily Johnson', 'action');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'John Smith', 'romance');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emily Johnson', 'action');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emma Wilson', 'action');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emma Wilson', 'action');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'John Smith', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'David Thompson', 'thriller');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'John Smith', 'romance');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'John Smith', 'adventure');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emily Johnson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emily Johnson', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'David Thompson', 'romance');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'David Thompson', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Emma Wilson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'David Thompson', 'romance');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'John Smith', 'drama');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'John Smith', 'romance');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emily Johnson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emily Johnson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'John Smith', 'mystery');
insert into songs (Title, Artist, Genre) values ('1984', 'John Smith', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'John Smith', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'David Thompson', 'romance');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Michael Davis', 'adventure');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emily Johnson', 'thriller');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emma Wilson', 'drama');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'John Smith', 'romance');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'John Smith', 'horror');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'David Thompson', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Michael Davis', 'adventure');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Michael Davis', 'romance');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emma Wilson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'John Smith', 'romance');
insert into songs (Title, Artist, Genre) values ('1984', 'Michael Davis', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'John Smith', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'David Thompson', 'romance');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Emily Johnson', 'romance');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emma Wilson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emily Johnson', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emma Wilson', 'action');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'John Smith', 'action');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Michael Davis', 'drama');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'David Thompson', 'romance');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Emma Wilson', 'romance');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Michael Davis', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'John Smith', 'thriller');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emily Johnson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emily Johnson', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Emily Johnson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('1984', 'David Thompson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emma Wilson', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'John Smith', 'mystery');
insert into songs (Title, Artist, Genre) values ('1984', 'John Smith', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emma Wilson', 'action');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'John Smith', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Emma Wilson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'David Thompson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Emma Wilson', 'adventure');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'John Smith', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Emma Wilson', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emily Johnson', 'romance');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emma Wilson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Michael Davis', 'action');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'John Smith', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'David Thompson', 'thriller');
insert into songs (Title, Artist, Genre) values ('1984', 'Emily Johnson', 'horror');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'John Smith', 'romance');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'David Thompson', 'action');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'John Smith', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'John Smith', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'David Thompson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emily Johnson', 'drama');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Michael Davis', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Michael Davis', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emily Johnson', 'action');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Emma Wilson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Emma Wilson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'John Smith', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'David Thompson', 'comedy');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emma Wilson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emma Wilson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Michael Davis', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Michael Davis', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'John Smith', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Emily Johnson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emma Wilson', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'John Smith', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Michael Davis', 'comedy');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emily Johnson', 'drama');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'John Smith', 'adventure');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Michael Davis', 'horror');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'John Smith', 'horror');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'David Thompson', 'action');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'David Thompson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'David Thompson', 'romance');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emily Johnson', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Michael Davis', 'thriller');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'David Thompson', 'thriller');
insert into songs (Title, Artist, Genre) values ('1984', 'Emma Wilson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emily Johnson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emma Wilson', 'mystery');
insert into songs (Title, Artist, Genre) values ('1984', 'John Smith', 'horror');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'David Thompson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'John Smith', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Emma Wilson', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'David Thompson', 'romance');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emma Wilson', 'drama');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'John Smith', 'action');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emma Wilson', 'action');
insert into songs (Title, Artist, Genre) values ('1984', 'Michael Davis', 'romance');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emma Wilson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Michael Davis', 'fantasy');
insert into songs (Title, Artist, Genre) values ('1984', 'Emily Johnson', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emily Johnson', 'action');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'David Thompson', 'comedy');
insert into songs (Title, Artist, Genre) values ('1984', 'John Smith', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('1984', 'Emma Wilson', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emma Wilson', 'romance');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Emily Johnson', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Michael Davis', 'drama');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'David Thompson', 'mystery');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emma Wilson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Michael Davis', 'romance');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'John Smith', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Emily Johnson', 'drama');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'John Smith', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Emily Johnson', 'adventure');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emily Johnson', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'John Smith', 'horror');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Emma Wilson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('1984', 'Emma Wilson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Michael Davis', 'comedy');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Michael Davis', 'thriller');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'David Thompson', 'thriller');
insert into songs (Title, Artist, Genre) values ('1984', 'John Smith', 'thriller');
insert into songs (Title, Artist, Genre) values ('1984', 'Emma Wilson', 'action');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'David Thompson', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'John Smith', 'adventure');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emma Wilson', 'drama');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'David Thompson', 'comedy');
insert into songs (Title, Artist, Genre) values ('1984', 'Emma Wilson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'David Thompson', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'David Thompson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Michael Davis', 'action');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Emma Wilson', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emily Johnson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emily Johnson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Michael Davis', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emma Wilson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Emma Wilson', 'romance');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'John Smith', 'romance');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'John Smith', 'thriller');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'David Thompson', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'John Smith', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'David Thompson', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'John Smith', 'action');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Michael Davis', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Michael Davis', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emily Johnson', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emma Wilson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emily Johnson', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'David Thompson', 'romance');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'David Thompson', 'drama');
insert into songs (Title, Artist, Genre) values ('1984', 'Emily Johnson', 'action');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Emily Johnson', 'mystery');
insert into songs (Title, Artist, Genre) values ('1984', 'John Smith', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'David Thompson', 'romance');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emily Johnson', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'David Thompson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'David Thompson', 'action');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emily Johnson', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'David Thompson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'John Smith', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emma Wilson', 'drama');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'John Smith', 'drama');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'David Thompson', 'action');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emily Johnson', 'adventure');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'David Thompson', 'action');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'David Thompson', 'mystery');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emily Johnson', 'horror');
insert into songs (Title, Artist, Genre) values ('1984', 'David Thompson', 'adventure');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Michael Davis', 'action');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emma Wilson', 'thriller');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'John Smith', 'romance');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'David Thompson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Michael Davis', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Emily Johnson', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'John Smith', 'thriller');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Michael Davis', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'John Smith', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emily Johnson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'David Thompson', 'adventure');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Michael Davis', 'fantasy');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Michael Davis', 'romance');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'David Thompson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('1984', 'Emma Wilson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'John Smith', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Michael Davis', 'adventure');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emma Wilson', 'action');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'John Smith', 'fantasy');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'David Thompson', 'thriller');
insert into songs (Title, Artist, Genre) values ('1984', 'Emily Johnson', 'drama');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'John Smith', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'David Thompson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'David Thompson', 'action');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'John Smith', 'adventure');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'David Thompson', 'adventure');
insert into songs (Title, Artist, Genre) values ('1984', 'David Thompson', 'romance');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'David Thompson', 'action');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Michael Davis', 'drama');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'John Smith', 'romance');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'John Smith', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Michael Davis', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'John Smith', 'action');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'David Thompson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'David Thompson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Michael Davis', 'comedy');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emily Johnson', 'drama');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'David Thompson', 'romance');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emma Wilson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'David Thompson', 'action');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Emily Johnson', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'David Thompson', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emily Johnson', 'action');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Michael Davis', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Michael Davis', 'action');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Michael Davis', 'horror');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emma Wilson', 'drama');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emily Johnson', 'drama');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emma Wilson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emily Johnson', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Michael Davis', 'romance');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'John Smith', 'romance');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'David Thompson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Emily Johnson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emma Wilson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Michael Davis', 'drama');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'John Smith', 'horror');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Michael Davis', 'drama');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Michael Davis', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Emily Johnson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emma Wilson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emily Johnson', 'action');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'John Smith', 'romance');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emma Wilson', 'drama');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Emily Johnson', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Emma Wilson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emily Johnson', 'action');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Emily Johnson', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'John Smith', 'romance');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emma Wilson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Emily Johnson', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Emily Johnson', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'David Thompson', 'romance');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emma Wilson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Emily Johnson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Michael Davis', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emma Wilson', 'drama');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'David Thompson', 'romance');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Michael Davis', 'action');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Emma Wilson', 'comedy');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emily Johnson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'John Smith', 'thriller');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'David Thompson', 'adventure');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emily Johnson', 'drama');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emily Johnson', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'John Smith', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'John Smith', 'thriller');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emily Johnson', 'mystery');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'David Thompson', 'action');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Michael Davis', 'horror');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'David Thompson', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Michael Davis', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'John Smith', 'romance');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'John Smith', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emily Johnson', 'comedy');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Michael Davis', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'David Thompson', 'horror');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Michael Davis', 'romance');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Michael Davis', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'David Thompson', 'comedy');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emma Wilson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Emily Johnson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emma Wilson', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'David Thompson', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Michael Davis', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emily Johnson', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emma Wilson', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'John Smith', 'horror');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'John Smith', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emily Johnson', 'adventure');
insert into songs (Title, Artist, Genre) values ('1984', 'Michael Davis', 'drama');
insert into songs (Title, Artist, Genre) values ('1984', 'Michael Davis', 'adventure');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emma Wilson', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Emma Wilson', 'romance');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'David Thompson', 'horror');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'David Thompson', 'mystery');
insert into songs (Title, Artist, Genre) values ('1984', 'Michael Davis', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'John Smith', 'drama');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'David Thompson', 'action');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Emma Wilson', 'romance');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'John Smith', 'drama');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emma Wilson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Michael Davis', 'romance');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'John Smith', 'mystery');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'David Thompson', 'mystery');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Michael Davis', 'drama');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'John Smith', 'comedy');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Michael Davis', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emma Wilson', 'drama');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emma Wilson', 'drama');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Michael Davis', 'mystery');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'David Thompson', 'action');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Emily Johnson', 'mystery');
insert into songs (Title, Artist, Genre) values ('1984', 'John Smith', 'romance');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Michael Davis', 'fantasy');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'Emma Wilson', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'John Smith', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emma Wilson', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Michael Davis', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'John Smith', 'romance');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emily Johnson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Emily Johnson', 'romance');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emma Wilson', 'mystery');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emily Johnson', 'adventure');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Michael Davis', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'David Thompson', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emily Johnson', 'action');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Michael Davis', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Emma Wilson', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emily Johnson', 'romance');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emily Johnson', 'mystery');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emily Johnson', 'action');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'John Smith', 'action');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Michael Davis', 'drama');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emma Wilson', 'mystery');
insert into songs (Title, Artist, Genre) values ('1984', 'David Thompson', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'Emma Wilson', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'David Thompson', 'adventure');
insert into songs (Title, Artist, Genre) values ('1984', 'Michael Davis', 'adventure');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emily Johnson', 'mystery');
insert into songs (Title, Artist, Genre) values ('1984', 'David Thompson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'Emily Johnson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Da Vinci Code', 'David Thompson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emma Wilson', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'John Smith', 'horror');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emily Johnson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Hunger Games', 'Michael Davis', 'horror');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'Emma Wilson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Michael Davis', 'horror');
insert into songs (Title, Artist, Genre) values ('Harry Potter and the Sorcerer''s Stone', 'John Smith', 'thriller');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'David Thompson', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emma Wilson', 'horror');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Michael Davis', 'comedy');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'David Thompson', 'mystery');
insert into songs (Title, Artist, Genre) values ('To Kill a Mockingbird', 'David Thompson', 'action');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emily Johnson', 'comedy');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'David Thompson', 'mystery');
insert into songs (Title, Artist, Genre) values ('The Lord of the Rings', 'Emily Johnson', 'adventure');
insert into songs (Title, Artist, Genre) values ('1984', 'Emma Wilson', 'horror');
insert into songs (Title, Artist, Genre) values ('Pride and Prejudice', 'John Smith', 'adventure');
insert into songs (Title, Artist, Genre) values ('The Catcher in the Rye', 'Emily Johnson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('The Hobbit', 'Emma Wilson', 'romance');
insert into songs (Title, Artist, Genre) values ('The Great Gatsby', 'Emily Johnson', 'action');
